entire code run

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -274,176 +274,176 @@ jobs:
             fi
       - destroy-envs
 
-  # deploy-frontend:
-  #   <<: *docker_node
-  #   steps:
-  #     - checkout
-  #     - install-python
-  #     - install-aws
-  #     - restore_cache:
-  #         keys: [frontend-deps]
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           export BACKEND_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output=text)
-  #           export API_URL="http://${BACKEND_IP}:3030"
-  #           echo "API_URL = ${API_URL}"
-  #           echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-  #           cat frontend/.env
-  #     - run:
-  #         name: Deploy frontend objects
-  #         command: |
-  #           cd frontend
-  #           npm install
-  #           npm run build
-  #           tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-  #           aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-  #     - revert-migrations
-  #     - destroy-envs
+  deploy-frontend:
+    <<: *docker_node
+    steps:
+      - checkout
+      - install-python
+      - install-aws
+      - restore_cache:
+          keys: [frontend-deps]
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output=text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      - revert-migrations
+      - destroy-envs
 
-  # deploy-backend:
-  #   <<: *docker_node
-  #   steps:
-  #     - checkout
-  #     - install-python
-  #     - install-ansible
-  #     - install-aws
-  #     - add_ssh_keys:
-  #         fingerprints:
-  #           - "e6:9f:36:3b:42:55:2a:df:7b:1a:44:a3:57:65:8b:6e"
-  #     - attach_workspace:
-  #         at: ~/
-  #     - restore_cache:
-  #         keys: [backend_deps]
-  #     - run:
-  #         name: Deploy backend
-  #         command: |
-  #           # your code here
-  #           cd backend
-  #           npm i
-  #           npm run build
-  #           cd ..
-  #           # Zip the directory
-  #           tar -C backend -czvf artifact.tar.gz .
-  #           cd .circleci/ansible
-  #           echo "Contents  of the inventory.txt file is -------"
-  #           cat inventory.txt
-  #           ansible-playbook -i inventory.txt deploy-backend.yml
-  #     - revert-migrations
-  #     - destroy-envs
+  deploy-backend:
+    <<: *docker_node
+    steps:
+      - checkout
+      - install-python
+      - install-ansible
+      - install-aws
+      - add_ssh_keys:
+          fingerprints:
+            - "c5:95:b7:9b:1c:99:34:87:c5:7c:f2:2c:37:3e:d9:45"
+      - attach_workspace:
+          at: ~/
+      - restore_cache:
+          keys: [backend_deps]
+      - run:
+          name: Deploy backend
+          command: |
+            # your code here
+            cd backend
+            npm i
+            npm run build
+            cd ..
+            # Zip the directory
+            tar -C backend -czvf artifact.tar.gz .
+            cd .circleci/ansible
+            echo "Contents  of the inventory.txt file is -------"
+            cat inventory.txt
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      - revert-migrations
+      - destroy-envs
 
-  #     # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure
 
-  # smoke-test:
-  #   <<: *docker_node
-  #   steps:
-  #     - checkout
-  #     - install-python
-  #     - install-aws
-  #     - run:
-  #         name: Get backend url and smoke test
-  #         command: |
-  #           export BACKEND_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output=text)
-  #           export API_URL="http://${BACKEND_IP}:3030"
-  #           echo "${API_URL}"
-  #           sleep 30s
-  #           if curl "${API_URL}/api/status" | grep "ok"
-  #           then
-  #               exit 0
-  #           else
-  #               exit 1
-  #           fi
-  #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
-  #           echo ${URL}
-  #           if curl -s ${URL} | grep "Welcome"
-  #           then
-  #               # Change this to 0 after the job fails
-  #             exit 0
-  #           else
-  #             exit 1
-  #           fi
-  #     - revert-migrations
-  #     - destroy-envs
-  #     # Here's where you will add some code to rollback on failure
+  smoke-test:
+    <<: *docker_node
+    steps:
+      - checkout
+      - install-python
+      - install-aws
+      - run:
+          name: Get backend url and smoke test
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances --query "Reservations[*].Instances[*].PublicIpAddress" --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output=text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            sleep 30s
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                exit 0
+            else
+                exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
+            echo ${URL}
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              exit 0
+            else
+              exit 1
+            fi
+      - revert-migrations
+      - destroy-envs
+      # Here's where you will add some code to rollback on failure
 
-  # cloudfront-update:
-  #   <<: *docker_node
-  #   steps:
-  #     - checkout
-  #     - install-python
-  #     - install-aws
-  #     - run:
-  #         name: Get old stack workflow id
-  #         command: |
-  #           # your code here
-  #           export OldWorkflowID=$(aws cloudformation \
-  #             list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-  #             --no-paginate --output text)
-  #           echo OldWorkflowID: "${OldWorkflowID}"
-  #           echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
-  #           # Fetch the stack names
-  #           export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-  #                   --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-  #           echo Stack names: "${STACKS[@]}"
-  #           echo "${STACKS[@]}" > stacks.txt
-  #           echo ${OldWorkflowID} > old_workflow.txt
-  #     - persist_to_workspace:
-  #         root: ~/
-  #         paths:
-  #           - project/old_workflow.txt
-  #           - project/stacks.txt
-  #     - run:
-  #         name: Update cloudfront distribution
-  #         command: |
-  #           aws cloudformation deploy \
-  #             --template-file .circleci/files/cloudfront.yml \
-  #             --stack-name InitialStack \
-  #             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-  #             --tags project=udapeople
-  #     # Here's where you will add some code to rollback on failure
-  #     - revert-migrations
-  #     - destroy-envs
+  cloudfront-update:
+    <<: *docker_node
+    steps:
+      - checkout
+      - install-python
+      - install-aws
+      - run:
+          name: Get old stack workflow id
+          command: |
+            # your code here
+            export OldWorkflowID=$(aws cloudformation \
+              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate --output text)
+            echo OldWorkflowID: "${OldWorkflowID}"
+            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+            # Fetch the stack names
+            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+                    --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+            echo Stack names: "${STACKS[@]}"
+            echo "${STACKS[@]}" > stacks.txt
+            echo ${OldWorkflowID} > old_workflow.txt
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/old_workflow.txt
+            - project/stacks.txt
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --stack-name InitialStack \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --tags project=udapeople
+      # Here's where you will add some code to rollback on failure
+      - revert-migrations
+      - destroy-envs
 
-  # cleanup:
-  #   <<: *docker_node
-  #   steps:
-  #     - checkout
-  #     - install-python
-  #     - install-aws
-  #     - attach_workspace:
-  #         at: ~/
-  #     - run:
-  #         name: Remove old stacks and files
-  #         command: |
-  #           export OldWorkflowID=$(cat old_workflow.txt)
-  #           export STACKS=$(cat stacks.txt)
-  #           echo Stack names: "${STACKS}"
-  #           echo OldWorkflowID: "${OldWorkflowID}"
-  #           if [[ ${STACKS} =~ ${OldWorkflowID} ]]
-  #           then
-  #             aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-  #             aws cloudformation delete-stack --stack-name "udapeople-backendinfra-${OldWorkflowID}"
-  #             aws cloudformation delete-stack --stack-name "udapeople-frontendinfra-${OldWorkflowID}"
-  #           else
-  #             echo "cannot delete old stacks"
-  #           fi
-  #     - revert-migrations
-  #     - destroy-envs
-  # deploy:
-  #   executor:
-  #     name: node/default
-  #   steps:
-  #     - checkout
-  #     - node/install-packages
-  #     - run:
-  #         command: npm run deploy
-  #     - slack/notify:
-  #         channel: A04129UBS1E
-  #         event: fail
-  #         template: basic_fail_1
+  cleanup:
+    <<: *docker_node
+    steps:
+      - checkout
+      - install-python
+      - install-aws
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Remove old stacks and files
+          command: |
+            export OldWorkflowID=$(cat old_workflow.txt)
+            export STACKS=$(cat stacks.txt)
+            echo Stack names: "${STACKS}"
+            echo OldWorkflowID: "${OldWorkflowID}"
+            if [[ ${STACKS} =~ ${OldWorkflowID} ]]
+            then
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              aws cloudformation delete-stack --stack-name "udapeople-backendinfra-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "udapeople-frontendinfra-${OldWorkflowID}"
+            else
+              echo "cannot delete old stacks"
+            fi
+      - revert-migrations
+      - destroy-envs
+  deploy:
+    executor:
+      name: node/default
+    steps:
+      - checkout
+      - node/install-packages
+      - run:
+          command: npm run deploy
+      - slack/notify:
+          channel: A04129UBS1E
+          event: fail
+          template: basic_fail_1
 
 workflows:
   default:
@@ -467,18 +467,18 @@ workflows:
           requires: [deploy-infrastructure]
       - run-migrations:
           requires: [configure-infrastructure]
-      # - deploy-frontend:
-      #     requires: [run-migrations]
-      # - deploy-backend:
-      #     requires: [run-migrations]
-      # - smoke-test:
-      #     requires:
-      #       - deploy-backend
-      #       - deploy-frontend
-      # - cloudfront-update:
-      #     requires: [smoke-test]
-      # - cleanup:
-      #     requires: [cloudfront-update]
-      # - deploy:
-      #    context: slack-secrets
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
+      - smoke-test:
+          requires:
+            - deploy-backend
+            - deploy-frontend
+      - cloudfront-update:
+          requires: [smoke-test]
+      - cleanup:
+          requires: [cloudfront-update]
+      - deploy:
+         context: slack-secrets
 
